name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for posting this issue. We'll get our 👀 on it soon."
        pr-message: "Thanks for posting this pull request. We'll get our 👀 on it soon."
